nodes:
  ##Wheel 1
  fl_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 0


  ##Wheel 2
  bl_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 0

  ##Wheel 3
  br_caster_rotation_joint:
    motor_layer:
      homing_event: 17 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 0

  ##Wheel 4
  fr_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 0
