nodes:
  fl_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "139350.5" # home offset

  bl_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "140000.0" # home offset

  fr_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-39500.0" # home offset
  br_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-38800" # home offset
