# node from which initial footprint is read
footprint_source: local_costmap_node/costmap

#
robot_base_frame: robot_1/base_link
# frames to check for footprint adjustment
frames_to_check: robot_1/base_footprint
epsilon: 0.01
