#raw4-0 for teleop-twist-joy

# axes
axis_linear:
  x: 1
  y: 0

scale_linear:
  x: 0.3
  y: 0.2

scale_linear_turbo:
  x: 0.6
  y: 0.4

axis_angular:
  yaw: 2

scale_angular:
  yaw: 0.3

scale_angular_turbo:
  yaw: 0.6

# buttons
enable_button: 5

#mode1: Base
enable_turbo_button: 7

